In [7]:
#Q10: Produce a list of facilities with a total revenue less than 1000.
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name as facility, 
SUM((CASE WHEN b.memid = 0 THEN f.guestcost 
               ELSE f.membercost END) * b.slots) AS revenue
FROM Members AS m
INNER JOIN Bookings AS b ON m.memid = b.memid
INNER JOIN Facilities AS f ON b.facid = f.facid
GROUP By f.name
HAVING revenue < 1000
ORDER BY revenue
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [9]:
#Q10: Produce a report of members and who recommended them in alphabetic surname,firstname order
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT m.firstname || ' ' || m.surname AS member, 
        r.firstname || ' ' || r.surname AS recommended
FROM Members AS m
INNER JOIN Members AS r ON r.memid = m.recommendedby
ORDER by m.surname
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Florence Bader', 'Ponder Stibbons')
('Anne Baker', 'Ponder Stibbons')
('Timothy Baker', 'Jemima Farrell')
('Tim Boothe', 'Tim Rownam')
('Gerald Butters', 'Darren Smith')
('Joan Coplin', 'Timothy Baker')
('Erica Crumpet', 'Tracy Smith')
('Nancy Dare', 'Janice Joplette')
('Matthew Genting', 'Gerald Butters')
('John Hunt', 'Millicent Purview')
('David Jones', 'Janice Joplette')
('Douglas Jones', 'David Jones')
('Janice Joplette', 'Darren Smith')
('Anna Mackenzie', 'Darren Smith')
('Charles Owen', 'Darren Smith')
('David Pinker', 'Jemima Farrell')
('Millicent Purview', 'Tracy Smith')
('Henrietta Rumney', 'Matthew Genting')
('Ramnaresh Sarwin', 'Florence Bader')
('Jack Smith', 'Darren Smith')
('Ponder Stibbons', 'Burton Tracy')
('Henry Worthington-Smyth', 'Tracy Smith')

In [10]:
#Q12: Find the facilities with their usage by member, but not guests
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT f.name AS facility, SUM( b.slots ) AS memberuse
FROM Facilities AS f
INNER JOIN Bookings AS b ON f.facid = b.facid
WHERE b.memid > 0
GROUP BY b.facid
ORDER BY memberuse DESC
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1086)
('Tennis Court 1', 957)
('Massage Room 1', 884)
('Tennis Court 2', 882)
('Snooker Table', 860)
('Pool Table', 856)
('Table Tennis', 794)
('Squash Court', 418)
('Massage Room 2', 54)

In [11]:
#Q13: Find the facilities usage by month, but not guests
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
SELECT strftime('%m',starttime) AS month,
m.firstname || ' ' || m.surname AS member,
SUM( b.slots ) AS totaluse
FROM Bookings AS b
INNER JOIN Members AS m ON b.memid = m.memid
WHERE b.memid > 0
GROUP BY month, member
ORDER BY month, member
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 'Burton Tracy', 41)
('07', 'Darren Smith', 255)
('07', 'Gerald Butters', 127)
('07', 'Janice Joplette', 137)
('07', 'Nancy Dare', 50)
('07', 'Tim Boothe', 42)
('07', 'Tim Rownam', 227)
('07', 'Tracy Smith', 182)
('08', 'Anna Mackenzie', 17)
('08', 'Anne Baker', 125)
('08', 'Burton Tracy', 225)
('08', 'Charles Owen', 185)
('08', 'Darren Smith', 249)
('08', 'David Jones', 134)
('08', 'David Pinker', 48)
('08', 'Florence Bader', 80)
('08', 'Gerald Butters', 166)
('08', 'Jack Smith', 102)
('08', 'Janice Joplette', 104)
('08', 'Jemima Farrell', 82)
('08', 'Matthew Genting', 18)
('08', 'Nancy Dare', 128)
('08', 'Ponder Stibbons', 127)
('08', 'Tim Boothe', 237)
('08', 'Tim Rownam', 242)
('08', 'Timothy Baker', 111)
('08', 'Tracy Smith', 151)
('09', 'Anna Mackenzie', 214)
('09', 'Anne Baker', 171)
('09', 'Burton Tracy', 100)
('09', 'Charles Owen', 160)
('09', 'Darren Smith', 181)
('09', 'David Farrell', 50)
('09', 'David Jones', 171)
('09', 'David Pinker', 111)
('09', 'Douglas Jones', 37)
('09', 'Erica Crumpet', 17)
('09', 'Florence Bader', 157)
('09', 'Gerald Butters', 116)
('09', 'Henrietta Rumney', 38)
('09', 'Henry Worthington-Smyth', 60)
('09', 'Hyacinth Tupperware', 28)
('09', 'Jack Smith', 117)
('09', 'Janice Joplette', 85)
('09', 'Jemima Farrell', 98)
('09', 'Joan Coplin', 106)
('09', 'John Hunt', 40)
('09', 'Matthew Genting', 113)
('09', 'Millicent Purview', 32)
('09', 'Nancy Dare', 89)
('09', 'Ponder Stibbons', 122)
('09', 'Ramnaresh Sarwin', 153)
('09', 'Tim Boothe', 161)
('09', 'Tim Rownam', 191)
('09', 'Timothy Baker', 179)
('09', 'Tracy Smith', 102)